import "oaidl.idl";
import "ocidl.idl";

[
	uuid(D15A484E-E145-461B-80B1-B6B8A5EF97C2),
	helpstring("Resource Interface"),
	version(1.0)
]
interface IResource : IUnknown
{

};

[
	uuid(2705FA1D-68BA-4E2B-92D4-846AE0A8D208),
	helpstring("Native Window Interface"),
	version(1.0)
]
interface INativeWindow : IUnknown
{
	[propget]
	HRESULT HasMaximize([out] BOOL* value);
	[propput]
	HRESULT HasMaximize([in] BOOL value);

	[propget]
	HRESULT Title([out]BSTR* value);
	[propput]
	HRESULT Title([in]BSTR value);

	[propget]
	HRESULT NativeHandle([out]INT_PTR* value);

	HRESULT Show();
	HRESULT Hide();
	HRESULT Close();
	HRESULT Destroy();
};

[
	uuid(2CABEDF6-D0CB-409D-A400-F03ACBF7663C),
	helpstring("Native Application Interface"),
	version(1.0)
]
interface INativeApplication : IUnknown
{
	HRESULT Run();
};

interface ISwapChain;
interface IRenderCommandBuffer;

[
	uuid(7316E516-0357-4F99-82D8-181F2BD289C6),
	helpstring("Renderable Object Interface"),
	version(1.0)
]
interface IRenderableObject : IUnknown
{
	HRESULT SetContent([in]IRenderCommandBuffer* buffer);
};

[
	uuid(D1BCE22E-1DA3-4183-B870-814EE56E1D37),
	helpstring("SwapChain Interface"),
	version(1.0)
]
interface ISwapChain : IUnknown
{

};

[
	uuid(B0FDA70A-53E1-419C-934C-F3588B722F32),
	helpstring("Render Command Buffer Interface"),
	version(1.0)
]
interface IRenderCommandBuffer : IUnknown
{
	HRESULT DrawGeometry([in]IResource* geometry);
};

typedef enum
{
	RT_LineGeometry
} ResourceType;

typedef struct
{
	float X, Y;
} Point;

typedef struct
{
	Point StartPoint;
	Point EndPoint;
} LineGeometryData;

[
	uuid(C8E784D3-3EBD-40D0-A421-55B3B52EF590),
	helpstring("Resource Container Interface"),
	version(1.0)
]
interface IResourceManager : IUnknown
{
	HRESULT CreateResource([in]ResourceType resType, [out, retval]IResource** res);
	HRESULT UpdateLineGeometry([in]IResource* res, [in]LineGeometryData* data);
	HRESULT CreateRenderCommandBuffer([out, retval]IRenderCommandBuffer ** buffer);
};

[
	uuid(CDFF5B2C-2CFB-4D80-A378-1B0F1AD95B41),
	helpstring("Device Context Interface"),
	version(1.0)
]
interface IDeviceContext : IUnknown
{
	HRESULT CreateSwapChain([in]INativeWindow* window, [out, retval]ISwapChain** swapChain);
	HRESULT CreateRenderableObject([out, retval]IRenderableObject** obj);
	HRESULT CreateResourceManager([out, retval]IResourceManager** resMgr);
};

[
	uuid(3E0658B5-F637-4BCD-9D0E-4A938970146D),
	helpstring("MPF.Platform Type Library"),
	version(1.0)
]
library MPFPlatformLibrary
{
}