import "oaidl.idl";
import "ocidl.idl";

[
	uuid(D15A484E-E145-461B-80B1-B6B8A5EF97C2),
	helpstring("Resource Interface"),
	version(1.0)
]
interface IResource : IUnknown
{

};

typedef struct
{
	float X, Y;
} Point;

[
	uuid(12DCA941-A675-4A79-81E0-2378753D6DAF),
	helpstring("Native Window Callback Interface"),
	version(1.0)
]
interface INativeWindowCallback : IUnknown
{
	HRESULT OnClosing();
	HRESULT OnLocationChanged([in]Point location);
	HRESULT OnSizeChanged([in]Point size);
};

[
	uuid(2705FA1D-68BA-4E2B-92D4-846AE0A8D208),
	helpstring("Native Window Interface"),
	version(1.0)
]
interface INativeWindow : IUnknown
{
	[propget]
	HRESULT HasMaximize([out] BOOL* value);
	[propput]
	HRESULT HasMaximize([in] BOOL value);

	[propget]
	HRESULT Title([out]BSTR* value);
	[propput]
	HRESULT Title([in]BSTR value);

	[propget]
	HRESULT NativeHandle([out]INT_PTR* value);
	
	[propget]
	HRESULT Location([out]Point* value);
	[propput]
	HRESULT Location([in]Point value);

	[propget]
	HRESULT Size([out]Point* value);
	[propput]
	HRESULT Size([in]Point value);

	[propget]
	HRESULT ClientSize([out]Point* value);

	HRESULT Show();
	HRESULT Hide();
	HRESULT Close();
	HRESULT Destroy();
};

[
	uuid(2CABEDF6-D0CB-409D-A400-F03ACBF7663C),
	helpstring("Native Application Interface"),
	version(1.0)
]
interface INativeApplication : IUnknown
{
	HRESULT Run();
};

interface ISwapChain;
interface IRenderCommandBuffer;

[
	uuid(7316E516-0357-4F99-82D8-181F2BD289C6),
	helpstring("Renderable Object Interface"),
	version(1.0)
]
interface IRenderableObject : IUnknown
{
	HRESULT SetOffset([in]float x, [in]float y);
	HRESULT SetContent([in]IRenderCommandBuffer* buffer);
	HRESULT Render();
};

[
	uuid(CF627173-9730-4030-944C-67C65442D2A1),
	helpstring("SwapChain Message Callback Interface"),
	version(1.0)
]
interface ISwapChainCallback : IUnknown
{
	HRESULT OnUpdate();
	HRESULT OnDraw();
};

[
	uuid(D1BCE22E-1DA3-4183-B870-814EE56E1D37),
	helpstring("SwapChain Interface"),
	version(1.0)
]
interface ISwapChain : IUnknown
{
	HRESULT SetCallback([in]ISwapChainCallback* callback);
};

[
	uuid(B0FDA70A-53E1-419C-934C-F3588B722F32),
	helpstring("Render Command Buffer Interface"),
	version(1.0)
]
interface IRenderCommandBuffer : IUnknown
{
	HRESULT DrawGeometry([in]IResource* geometry, [in]IResource* pen, [in]IResource* brush, [in]float* values);
};

typedef enum
{
	RT_LineGeometry,
	RT_RectangleGeometry,
	RT_PathGeometry,
	RT_SolidColorBrush,
	RT_Pen
} ResourceType;

typedef struct
{
	float A, R, G, B;
} ColorF;

typedef struct
{
	Point StartPoint;
	Point EndPoint;
} LineGeometryData;

typedef struct
{
	Point LeftTop;
	Point RightBottom;
} RectangleGeometryData;

interface IResourceManager;

typedef struct
{
	UINT16 DesignUnitsPerEM;
	UINT16 Ascent;
	UINT16 Descent;
	INT16 LineGap;
	UINT16 CapHeight;
	UINT16 XHeight;
	INT16 UnderlinePosition;
	INT16 UnderlineThickness;
	INT16 StrikethroughPosition;
	UINT16 StrikethroughThickness;
} FontMetrics;

typedef struct
{
	INT32 LeftSideBearing;
	UINT32 AdvanceWidth;
	INT32 RightSideBearing;
	INT32 TopSideBearing;
	UINT32 AdvanceHeight;
	INT32 BottomSideBearing;
	INT32 VerticalOriginY;
} GlyphMetrics;

[
	uuid(E9B540D3-DF9B-4619-9251-886AC2B86646),
	helpstring("Font Face Interface"),
	version(1.0)
]
interface IFontFace : IUnknown
{
	[propget]
	HRESULT FaceCount([out, retval]UINT* value);

	[propget]
	HRESULT FontMetrics([out, retval]FontMetrics* value);

	[propget]
	HRESULT UnitsPerEM([out, retval]UINT* value);

	HRESULT CreateGlyphGeometry([in]IResourceManager* resMgr, [in]UINT unicode, [out]GlyphMetrics* metrics, [out, retval]IResource** geometry);
};

[
	uuid(C8E784D3-3EBD-40D0-A421-55B3B52EF590),
	helpstring("Resource Container Interface"),
	version(1.0)
]
interface IResourceManager : IUnknown
{
	HRESULT CreateRenderCommandBuffer([out, retval]IRenderCommandBuffer ** buffer);
	HRESULT CreateFontFaceFromMemory([in]INT_PTR buffer, [in]UINT64 size, [in]UINT faceIndex, [out, retval]IFontFace ** fontFace);
	HRESULT CreateResource([in]ResourceType resType, [out, retval]IResource** res);
	HRESULT UpdateLineGeometry([in]IResource* res, [in]LineGeometryData* data);
	HRESULT UpdateRectangleGeometry([in]IResource* res, [in]RectangleGeometryData* data);
	HRESULT UpdatePathGeometry([in]IResource* res, [in, size_is(length)]byte* data, [in]UINT32 length);
	HRESULT UpdateSolidColorBrush([in]IResource* res, [in]ColorF* color);
	HRESULT UpdatePen([in]IResource* res, [in]float thickness, [in]IResource* brush);
};

[
	uuid(B82A3B78-E27D-41B3-8EDE-6190D2FFD261),
	helpstring("Device Context Callback Interface"),
	version(1.0)
]
interface IDeviceContextCallback : IUnknown
{
	HRESULT OnRender();
};

[
	uuid(CDFF5B2C-2CFB-4D80-A378-1B0F1AD95B41),
	helpstring("Device Context Interface"),
	version(1.0)
]
interface IDeviceContext : IUnknown
{
	HRESULT CreateSwapChain([in]INativeWindow* window, [out, retval]ISwapChain** swapChain);
	HRESULT CreateRenderableObject([out, retval]IRenderableObject** obj);
	HRESULT CreateResourceManager([out, retval]IResourceManager** resMgr);
};

[
	uuid(3E0658B5-F637-4BCD-9D0E-4A938970146D),
	helpstring("MPF.Platform Type Library"),
	version(1.0)
]
library MPFPlatformLibrary
{
}